CQCL/pytket-docs

examples/README.md
This README.md file is missing links to new example notebooks and has outdated links to previous example notebooks.
=> Update README.md in examples folder

.github/workflows/check-examples.yml, .github/workflows/check-manual.yml
The weekly scheduled runs were always failing because we hadn't checked out the repo. (I guess this is automatic for pull requests.)
=> Check out repo before running changes filter.

.github/workflows/check-examples.yml, .github/workflows/check-manual.yml
Otherwise these scripts fail with an error on the scheduled build because they don't find the default branch (not sure why).
=> Specify base branch for CI checks.

build-manual
I'm solving an issue that appeared on some non-Linux systems, due to the non-standard usage of `\n` in `sed`. (see comments in https://unix.stackexchange.com/a/13716). 
I haven't found a readable cross-platform solution with `sed` so I switched to `awk` instead, hoping that works for everyone.
=> [docs] Fixed `build-manual` for MacOS

manual/index-rst-template
Fixes [TKET-1660](https://cqc.atlassian.net/browse/TKET-1660?atlOrigin=eyJpIjoiNGU3NDQwZDBiZDNiNGNkZjg4ZTUyZTc0NGExZGZkOGUiLCJwIjoiaiJ9).
This PR addresses adding a link to the main `pytket` documentation website in the side bar of the manual in the same fashion as the `pytket-extensions` [website](https://cqcl.github.io/pytket-extensions/api/index.html).
=> [TKET-1660] Add a link to pytket documentation website.

manual/manual_compiler.rst
A test PR for editing the manual.
Previously The EulerAngleReduction example shown in the manual did not reduce the number of single qubit rotations.
With these minor changes EulerAngleReduction squashes the number of rotation gates from 5 to 3.
=>  fixed Euler

docs/manual/manual_compiler.html, manual/manual_compiler.rst
I've added a brief manual section on Alec's `CustomPass` feature. I've put this under advanced topics, let me know if this is the appropriate place.
The pass I've defined performs a pretty trivial transformation from Z to {X,H} and otherwise does nothing. I'm not that satisfied with the function as it feels overly complex for something so simple. Let me know if another example would be preferred.
I've tried out more interesting transformations but maybe its best to go with something easy for the manual.
=> Custom passdocs

.github/workflows/check-manual.yml
Added a line to the check manual workflow to ensure that the CI run continues on error instead of quitting. 
This is so that we can see error messages on the CI instead of the build just failing.
=> add continue-on-error: true

.github/workflows/check-manual.yml
Reverts CQCL/pytket#190
remove `continue-on-error: true` from build-manual
=> Revert "add continue-on-error: true"

.github/workflows/check-manual.yml, docs/manual/manual_compiler.html, manual/manual_compiler.rst
REDO of pervious PR due to a git mistake - hopefully I got everything.
Edits to the compiler section of the manual
**Changes**
Fixed confusing default pass example - this was originally showing extra gates being introduced at higher levels of optimisation when compiling to `AerBackend` . I've also added some explanation of the different levels of optimisation below
I've added a short section on `UserdefinedPredicate` which was previously missing.
I've edited the documentation on `FullPeepholeOptimise` to avoid explicit reference to the passes applied. This is because the order varies depending on the target gateset and the implementation may change over time.
I've also made some minor changes to the spacing and layout of this section.
=> Edit compiler manual

docs/manual/manual_compiler.html, manual/manual_compiler.rst
Will pointed out an issue with the Predicates table in dark mode after https://github.com/CQCL/pytket/pull/230. The text in the predicates table [here](https://cqcl.github.io/pytket/manual/manual_compiler.html#predicates) was showing in black making it hard to read.
I'm not sure what the cause of this is but changing the spacing in the table seems to resolve the issue in my local build.
=> Fix issue with Predicates table in dark mode 

docs/manual/manual_circuit.html, manual/manual_circuit.rst
Here I've added some manual content on the new types of box available in pytket. These include `StatePreparationBox` and the various kinds of multiplexor operations.
After some discussion with @cqc-alec I've decided that some of the content in https://github.com/CQCL/pytket/pull/231 was more appropriate for the user manual. A lot of the content in this PR is ported from the orignial PR in the examples repo.
I've added some content on `PhasePolyBox` as this was previously undocumented. I'm not so familar with this one so let me know if I've explained it correctly.
I've also tweaked (and hopefully Improved) the existing docs on `CircBox` and `PauliExpBox`.
I've reordered sections so that the analysing circuits section comes before the section on boxes. This is because I wanted to make use …
=> Boxes update

docs/manual/manual_backend.html, docs/manual/manual_circuit.html, docs/manual/manual_compiler.html, manual/conf.py, manual/manual_backend.rst, manual/manual_circuit.rst, manual/manual_compiler.rst
Small PR to fix the two broken svg images in the circuit section of the manual.
I think there was some caching problem when I pushed the built html in https://github.com/CQCL/pytket/pull/236
I've rebuilt the html and it looks fine.
EDIT: I've also made use of the `sphinx.ext.autosectionlabel` to link to section headings. This then raised warnings about some duplicate headings we have e.g. "advanced topics". I have now modified these headings to remove these warnings
=> Fix diagrams and Update Headings 

examples/_config.yml, examples/_toc.yml
Removing a single notebook from execution as it seems to time out unpredictably causing issues with the build.
=> don't execute qujax classification example

examples/_config.yml
This is a temporary workaround to try and stop the CI failures here 
I'm having trouble pulling the latest commits on the `example/QPE` branch for [this PR](https://github.com/CQCL/pytket/pull/241/).
Not sure how else to resolve the issue.
=> temporarily exclude QPE notebook

docs/manual/index.html
After https://github.com/CQCL/pytket/pull/264 the formatting of the manual index page was messed up.
This is because I did not push the html page after addressing the requested changes to the requirements file.
It now looks like this locally.
I've added the built html page. This sort of thing should never happen once the manual is built on CI.
=> Fix requirements shown in manual index page

docs/404.html
This also redirects, like docs/index.html, so this should catch any other links people have to pages on https://cqcl.github.io/pytket/.
=> Add docs/404.html

.gitignore, manual/README.md
Updating the README after the changes made in https://github.com/CQCL/pytket/pull/268.
I've also added the `docs/manual` directory to `.gitignore`. This avoids cluttering source control when building the manual locally.
=> Update README and add `docs/manual` to gitignore

.gitignore, build-manual, manual/README.md
Follows some discussion in #272 
**Changes**
1. Installs `ipykernel` in `build-manual` script.
2. Removed the copying of the `manual/build` directory into the `docs/manual` directory. I've also removed the `docs/manual` from `.gitignore`.
**A question**
Wouldn't it be simpler if the `check-manual` workflow used the `build-manual` script directly? We have essentially the same build commands in multiple places.
=> Install `ipykernel` in docs build and remove duplication

.github/workflows/check-manual.yml, manual/conf.py
In addition to this, I also had to turn off warnings-as-errors for `sphinx-build`. Otherwise the build fails with an obscure warning:
```
/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/cotengra/hyperoptimizers/hyper.py:34: UserWarning: Couldn't import `kahypar` - skipping from default hyper optimizer and using basic `labels` method instead.
```
=> Correct intersphinx config for pytket docs.

.github/workflows/check-manual.yml, build-manual, manual_constraints.txt
Pinning scipy to v1.12.0 for now to fix the manual build.
Also removing the flag to fail the build on warnings as I am getting this warning locally.
```
Warning, treated as error:
Cell printed to stderr:
/Users/callum/Desktop/pytket-docs/.venv/lib/python3.11/site-packages/cotengra/hyperoptimizers/hyper.py:34: UserWarning: Couldn't import `kahypar` - skipping from default hyper optimizer and using basic `labels` method instead.
warnings.warn(
```
I'm not sure we can do anything about this for now.
Note that the manual is now built on CI correctly after https://github.com/CQCL/pytket-docs/pull/315/commits/277061c443161d15e6da9978acb4a83246a8360b (the build is no longer skipped for pushes). This explains why the CI build wasn't failing but local builds were.
We should also remove the scipt …
=> Pin scipy version to fix manual build and run build as a CI check

.github/workflows/check-manual.yml
Adding a flag to fail the manual build on warnings. This is consistent wiht the tket website build and the local `./build-manual` script.
Ensures that warnings from the local build are caught by the CI checks.
Please mention any github issues addressed by this PR.
=> Add flag to fail manual CI build on warnings 

manual/manual_circuit.rst
The spacing in the multiplexor table was messed up. It looks particularly bad in dark mode. Probably due to a change in #309.
Also fixed a typo and made some minor formatting fixes.
Before 
After (local build)
Please mention any github issues addressed by this PR.
=> Fix spacing in multiplexor table

manual/manual_backend.rst
This example snippet was erroring out causing the manual build to fail. Seems the circuit was always valid for `AerBackend` and so the `compiled_circ` variable was unreachable. Not sure what changed here to explain this.
In any case I've updated the snippet so that the original circuit has a CnRy gate which needs to be compiled down for the circuit to be valid for `AerBackend`.
Please mention any github issues addressed by this PR.
=> fix: update faulty manual example on `AerBackend` compilation

examples/_config.yml
Extending the jupyterbook timeout to 120s as some of the examples are very close to the 90s per cell limit. This was  issues with the website build. The build was erroring out on certain runs. 
I think the ucc_vqe example and possibly the pytket-qujax qaoa examples are the offenders.
=> infra: Extend jupyterbook build timeount

examples/example_requirements.txt, manual_requirements.txt
Website build is failing as the dependencies are hardcoded in this repository.
Dependencies are reorganised in #339
=> update pytket versions to 1.31

.github/workflows/check-docs-build.yml
Fixes the C.I. build of the docs to always run on pull requests. I think after #339 I hadn't updated the workflow correctly so the C.I. checks were skipped. This was because of the way the filtering was set up.
I have solved this for now by removing the "changes" job in C.I. that does the filtering. Let me know if there are any objections to this. I think we would want to run C.I. for most changes we make in this repository anyway. I think the only files I it would make sense to skip the checks for are README files, the licence file and `.gitignore`
Alternatively I could update the filtering to check for updates to the new files.
This PR should be merged before #370  to be on the safe side.
Fixes #368
=> fix: Run C.I. checks for the docs build on PRs

docs/manual/manual_zx.md
ZX table was invalidated by bad syntax. Likely introduced in [#366 ](https://github.com/CQCL/pytket-docs/pull/370)
Before
After
=> fix: update broken ZX rewrite table

.github/workflows/issue_to_project.yml
Adding an issue to the gh-project board was failing due to the name of the org being outdated.
https://github.com/CQCL/pytket-docs/actions/runs/12414509338
Please mention any github issues addressed by this PR.
=> ci: update github org name (`CQCL-DEV` -> `quantinuum-dev`)

docs/manual/manual_intro.md
This link is timing out the link checker causing the website build to fail.
=> fix: replace flaky link to paper
